services:
  go_backend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - USERNAME=akif
      - PASSWORD=akif
      - URL=cluster0te.k23az.mongodb.net
    ports:
      - 8080:8080